"""empty message

Revision ID: feb6f8c1c9d6
Revises: e40ce90d641e
Create Date: 2018-03-01 09:41:29.107175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb6f8c1c9d6'
down_revision = 'e40ce90d641e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'create_date')
    # ### end Alembic commands ###
